/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cocina;

import java.sql.Statement;
import conexion.ConexionBD;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Melanie Guzmán
 */
public class InterfazCocina extends javax.swing.JFrame {
    String [] datos = new String[3];
    /**
     * Creates new form InterfazCocina
     */
    public InterfazCocina() {
        initComponents();
    mostrar();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idComanda");
        model.addColumn("idPlatillo");
        model.addColumn("Cantidad");
        TablaProceso.setModel(model);
        
    }
    public void mostrar(){
        int idComanda = 0, idPlatillo = 0, cantidadPlatillo = 0;
        String sql = "select idComanda, idPlatillo, cantidad FROM platillosporcomanda";
        Statement st;
        ConexionBD conn = new ConexionBD();
        Connection ConexionBD = conn.getConnection();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idComanda");
        model.addColumn("idPlatillo");
        model.addColumn("Cantidad");
        TablaEntrada.setModel(model);
        
        try{
            st=ConexionBD.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                model.addRow(datos);
        }
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error"+ e.toString());
            }
        
        }
    public void mostrar1(){
        int idComanda = 0, idPlatillo = 0, cantidadPlatillo = 0;
        String sql = "select idComanda, idPlatillo, cantidad FROM platillosporcomanda";
        Statement st;
        ConexionBD conn = new ConexionBD();
        Connection ConexionBD = conn.getConnection();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("idComanda");
        model.addColumn("idPlatillo");
        model.addColumn("Cantidad");
        TablaProceso.setModel(model);
        try{
            st=ConexionBD.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                model.addRow(datos);
        }
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error"+ e.toString());
            }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnOrden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEntrada = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProceso = new javax.swing.JTable();
        btnOrdenLista = new javax.swing.JButton();
        MenuCocina = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        IngreMenu = new javax.swing.JMenu();
        InterIngre = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solicitar Orden");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText(">>>");

        BtnOrden.setText("Pasar Orden");
        BtnOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrdenActionPerformed(evt);
            }
        });

        TablaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEntrada);

        TablaProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaProceso);

        btnOrdenLista.setText("Orden Lista");
        btnOrdenLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnOrden))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrdenLista)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOrden))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnOrdenLista)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu1.setText("Control");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Control Ingredientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        MenuCocina.add(jMenu1);

        IngreMenu.setText("Recetas");

        InterIngre.setText("Platillos");
        InterIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterIngreActionPerformed(evt);
            }
        });
        IngreMenu.add(InterIngre);

        jMenuItem1.setText("Postres");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        IngreMenu.add(jMenuItem1);

        MenuCocina.add(IngreMenu);

        setJMenuBar(MenuCocina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrdenActionPerformed
        // TODO add your handling code here:
        mostrar1();
        //insert into platillosporcomanda (`idComanda`,`idPlatillo`,`cantidad`) values (1, 1, 3);
    }//GEN-LAST:event_BtnOrdenActionPerformed

    private void InterIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterIngreActionPerformed
        InterfazPlatillos abrir = new InterfazPlatillos();
        abrir.setVisible(true);
    }//GEN-LAST:event_InterIngreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        InterfazPostres abrir = new InterfazPostres();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnOrdenListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenListaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Orden lista");
    }//GEN-LAST:event_btnOrdenListaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        InterfazControl_Ingr abrir = new InterfazControl_Ingr();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOrden;
    private javax.swing.JMenu IngreMenu;
    private javax.swing.JMenuItem InterIngre;
    private javax.swing.JMenuBar MenuCocina;
    private javax.swing.JTable TablaEntrada;
    private javax.swing.JTable TablaProceso;
    private javax.swing.JButton btnOrdenLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
